// Mock data for MVP — renders the site without a database connection.
// Replace with Prisma queries once Supabase is connected.

export interface MockAsset {
  id: string;
  publicId: string;
  stockId: string;
  slug: string;
  type: "IMAGE" | "VIDEO";
  status: "PUBLISHED" | "DRAFT" | "ARCHIVED";
  title: string;
  subtitle?: string;
  description: string;
  story?: string;
  imageContent?: string;
  seoTitle?: string;
  seoDescription?: string;
  displayPrice: string;
  thumbnailUrl: string;
  previewUrl: string;
  width: number;
  height: number;
  resolution: string;
  camera?: string;
  lens?: string;
  iso?: string;
  aperture?: string;
  focalLength?: string;
  shutterSpeed?: string;
  country?: string;
  city?: string;
  location?: string;
  copyrightOwner: string;
  copyrightYear: number;
  licenseType: string;
  publicContactEmail?: string;
  publicContactWebsite?: string;
  rightsHolders?: MockRightsHolder[];
  views: number;
  likes: number;
  downloads: number;
  favorites: number;
  popularity: number;
  shootDate: string;
  publishDate: string;
  createdAt: Date;
  updatedAt?: Date;
  categoryName: string;
  collectionName?: string;
  tags: string[];
  // Video-specific
  duration?: number;
  fps?: string;
  codec?: string;
}

export type MockRightsHolderRole =
  | "COPYRIGHT_OWNER"
  | "AUTHORIZED_REPRESENTATIVE"
  | "ARCHIVE_CUSTODIAN";

export interface MockRightsHolder {
  name: string;
  role: MockRightsHolderRole;
  organization?: string;
  email?: string;
  website?: string;
}

// High-quality Unsplash images for the editorial look
const DEMO_IMAGES: MockAsset[] = [
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567001",
    publicId: "7391826415028",
    stockId: "IMG-2015-000001",
    slug: "golden-hour-portrait",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Golden Hour Portrait",
    subtitle: "Florence, Italy · 2015",
    description: "A captivating portrait captured during the golden hour, with warm natural light creating soft shadows and a luminous glow across the subject's features.",
    story: "Shot at Piazzale Michelangelo overlooking the Arno River, this portrait captures the essence of Italian light at its most beautiful — the brief window when the sun melts into gold.",
    imageContent: "Close-up portrait of a young woman bathed in warm golden-hour light, soft bokeh background of rolling Tuscan hills.",
    seoTitle: "Golden Hour Portrait — Original Editorial Photography",
    seoDescription: "Original fine art portrait captured in Florence, Italy. Rights managed photograph by ARCHI.",
    displayPrice: "$299.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=1200&q=90",
    width: 4000,
    height: 6000,
    resolution: "4000 × 6000",
    camera: "Canon EOS R5",
    lens: "RF 85mm f/1.2L USM",
    iso: "200",
    aperture: "f/1.4",
    focalLength: "85mm",
    shutterSpeed: "1/250s",
    country: "Italy",
    city: "Florence",
    location: "Piazzale Michelangelo",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "RIGHTS_MANAGED",
    publicContactEmail: "archive@archi.studio",
    publicContactWebsite: "https://archi.studio",
    rightsHolders: [
      { name: "ARCHI Rights Office", role: "COPYRIGHT_OWNER", organization: "ARCHI Studio" },
      { name: "Elena Marlow", role: "AUTHORIZED_REPRESENTATIVE", organization: "Marlow Creative Rights" },
      { name: "ARCHI Registry", role: "ARCHIVE_CUSTODIAN", organization: "ARCHI Studio", email: "archive@archi.studio", website: "https://archi.studio" },
    ],
    views: 12450,
    likes: 834,
    downloads: 156,
    favorites: 420,
    popularity: 9200,
    shootDate: "2015-03-15",
    publishDate: "2015-03-20",
    createdAt: new Date("2015-03-20"),
    categoryName: "Portraits",
    collectionName: "Italian Light",
    tags: ["portrait", "golden hour", "natural light", "editorial", "florence"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567002",
    publicId: "8201746153928",
    stockId: "IMG-2016-000002",
    slug: "architectural-symmetry",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Architectural Symmetry",
    subtitle: "Valencia, Spain · 2016",
    description: "Clean geometric lines and perfect symmetry in modern architecture. The interplay of light and shadow creates a minimalist composition that challenges perception.",
    imageContent: "Wide-angle interior view of the City of Arts and Sciences, showcasing perfect bilateral symmetry with white concrete arches reflecting in still water.",
    displayPrice: "$199.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=1200&q=90",
    width: 5472,
    height: 3648,
    resolution: "5472 × 3648",
    camera: "Sony A7R V",
    lens: "FE 24-70mm f/2.8 GM II",
    iso: "100",
    aperture: "f/8",
    focalLength: "24mm",
    shutterSpeed: "1/60s",
    country: "Spain",
    city: "Valencia",
    location: "City of Arts and Sciences",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "RIGHTS_MANAGED",
    views: 8920,
    likes: 612,
    downloads: 89,
    favorites: 305,
    popularity: 6800,
    shootDate: "2016-02-10",
    publishDate: "2016-02-15",
    createdAt: new Date("2016-02-15"),
    categoryName: "Architecture",
    collectionName: "Modern Forms",
    tags: ["architecture", "minimalist", "symmetry", "modern", "spain"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567003",
    publicId: "5621847394102",
    stockId: "IMG-2015-000003",
    slug: "ocean-mist-landscape",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Ocean Mist Landscape",
    subtitle: "Cabo da Roca, Portugal · 2015",
    description: "Ethereal coastal landscape where ocean mist meets the rocky shoreline at dawn. Long exposure creates a dreamlike quality where water becomes silk.",
    imageContent: "Long-exposure seascape at dawn, rocky Atlantic coastline with silky mist hovering above dark rocks, dramatic gradient sky from deep blue to warm amber.",
    displayPrice: "$349.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=1200&q=90",
    width: 6000,
    height: 4000,
    resolution: "6000 × 4000",
    camera: "Nikon Z9",
    lens: "NIKKOR Z 14-24mm f/2.8 S",
    iso: "64",
    aperture: "f/11",
    focalLength: "14mm",
    shutterSpeed: "30s",
    country: "Portugal",
    city: "Sintra",
    location: "Cabo da Roca",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "RIGHTS_MANAGED",
    views: 15600,
    likes: 1205,
    downloads: 234,
    favorites: 678,
    popularity: 12400,
    shootDate: "2015-01-22",
    publishDate: "2015-01-28",
    createdAt: new Date("2015-01-28"),
    categoryName: "Landscapes",
    collectionName: "Coastal Series",
    tags: ["landscape", "ocean", "long exposure", "dawn", "portugal"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567004",
    publicId: "9314628507461",
    stockId: "IMG-2017-000004",
    slug: "street-life-tokyo",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Street Life Tokyo",
    subtitle: "Shibuya, Japan · 2017",
    description: "The pulse of Tokyo captured in a single frame. Neon reflections on rain-soaked streets create an atmosphere of urban poetry.",
    imageContent: "Night street photography in Shibuya, Tokyo. Crowds of pedestrians under glowing neon signs, rain-reflective pavement creating a mirror of city lights.",
    displayPrice: "$249.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=1200&q=90",
    width: 4288,
    height: 2848,
    resolution: "4288 × 2848",
    camera: "Leica Q3",
    lens: "Summilux 28mm f/1.7",
    iso: "800",
    aperture: "f/2.0",
    focalLength: "28mm",
    shutterSpeed: "1/60s",
    country: "Japan",
    city: "Tokyo",
    location: "Shibuya",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "EDITORIAL",
    views: 21300,
    likes: 1870,
    downloads: 312,
    favorites: 945,
    popularity: 18500,
    shootDate: "2017-04-05",
    publishDate: "2017-04-10",
    createdAt: new Date("2017-04-10"),
    categoryName: "Street",
    collectionName: "Urban Stories",
    tags: ["street", "tokyo", "urban", "night", "rain"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567005",
    publicId: "4837291650284",
    stockId: "IMG-2018-000005",
    slug: "botanical-details",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Botanical Details",
    subtitle: "Hortus Botanicus, Netherlands · 2018",
    description: "Intimate macro photography revealing the intricate textures and patterns hidden within botanical specimens. Nature's geometry laid bare.",
    imageContent: "Extreme close-up macro of an open tulip blossom, soft pink petals with delicate veining, shallow depth of field with creamy bokeh background.",
    displayPrice: "$179.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=90",
    width: 5184,
    height: 3456,
    resolution: "5184 × 3456",
    camera: "Canon EOS R5",
    lens: "RF 100mm f/2.8L Macro IS USM",
    iso: "400",
    aperture: "f/4",
    focalLength: "100mm",
    shutterSpeed: "1/200s",
    country: "Netherlands",
    city: "Leiden",
    location: "Hortus Botanicus",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "ROYALTY_FREE",
    views: 6780,
    likes: 432,
    downloads: 67,
    favorites: 198,
    popularity: 5200,
    shootDate: "2018-05-12",
    publishDate: "2018-05-18",
    createdAt: new Date("2018-05-18"),
    categoryName: "Macro",
    tags: ["botanical", "macro", "nature", "texture", "flowers"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567006",
    publicId: "7482916538470",
    stockId: "IMG-2016-000006",
    slug: "desert-solitude",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Desert Solitude",
    subtitle: "Erg Chebbi, Morocco · 2016",
    description: "Vast desert landscape under a dramatic sky. The endless dunes create sweeping lines that draw the eye toward the horizon, where earth meets sky in perfect silence.",
    imageContent: "Aerial-perspective view across undulating Sahara sand dunes at golden hour. Perfect sinuous lines cast deep shadows, lone camel caravan in the far distance.",
    displayPrice: "$399.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&q=90",
    width: 6000,
    height: 4000,
    resolution: "6000 × 4000",
    camera: "Hasselblad X2D 100C",
    lens: "XCD 21mm f/4",
    iso: "100",
    aperture: "f/8",
    focalLength: "21mm",
    shutterSpeed: "1/250s",
    country: "Morocco",
    city: "Merzouga",
    location: "Erg Chebbi",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "RIGHTS_MANAGED",
    views: 18200,
    likes: 1540,
    downloads: 278,
    favorites: 812,
    popularity: 15600,
    shootDate: "2016-02-28",
    publishDate: "2016-03-05",
    createdAt: new Date("2016-03-05"),
    categoryName: "Landscapes",
    collectionName: "Coastal Series",
    tags: ["desert", "landscape", "minimal", "sand dunes", "sahara"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567007",
    publicId: "2954867310562",
    stockId: "IMG-2019-000007",
    slug: "artisan-workshop",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Artisan Workshop",
    subtitle: "Vieux Lyon, France · 2019",
    description: "A master craftsman at work in his traditional workshop, surrounded by decades of tools and materials that tell stories of dedication and precision.",
    imageContent: "Documentary photograph of an elderly French bookbinder at his cluttered workshop bench, hands working leather with a bone folder, warm amber workshop light.",
    displayPrice: "$229.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=1200&q=90",
    width: 4896,
    height: 3264,
    resolution: "4896 × 3264",
    camera: "Fujifilm GFX 100S",
    lens: "GF 80mm f/1.7 R WR",
    iso: "1600",
    aperture: "f/2.0",
    focalLength: "80mm",
    shutterSpeed: "1/80s",
    country: "France",
    city: "Lyon",
    location: "Vieux Lyon",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "EDITORIAL",
    views: 9450,
    likes: 678,
    downloads: 123,
    favorites: 356,
    popularity: 7900,
    shootDate: "2019-06-08",
    publishDate: "2019-06-12",
    createdAt: new Date("2019-06-12"),
    categoryName: "Documentary",
    collectionName: "Craft & Tradition",
    tags: ["documentary", "craftsman", "workshop", "artisan", "france"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567008",
    publicId: "6173849205637",
    stockId: "IMG-2020-000008",
    slug: "abstract-motion",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Abstract Motion",
    subtitle: "Berlin, Germany · 2020",
    description: "An exploration of movement through intentional camera motion, transforming ordinary scenes into abstract compositions of color and light.",
    imageContent: "ICM (intentional camera movement) abstract photograph, vertical light trails of yellow and blue streaks against dark background, painterly texture.",
    displayPrice: "$159.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=1200&q=90",
    width: 4000,
    height: 6000,
    resolution: "4000 × 6000",
    camera: "Sony A7 IV",
    lens: "FE 70-200mm f/2.8 GM II",
    iso: "100",
    aperture: "f/16",
    focalLength: "200mm",
    shutterSpeed: "1/4s",
    country: "Germany",
    city: "Berlin",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "ROYALTY_FREE",
    views: 5340,
    likes: 389,
    downloads: 45,
    favorites: 167,
    popularity: 4100,
    shootDate: "2020-04-20",
    publishDate: "2020-04-25",
    createdAt: new Date("2020-04-25"),
    categoryName: "Fine Art",
    tags: ["abstract", "motion", "experimental", "color", "icm"],
  },
  // New assets
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567009",
    publicId: "3829164750293",
    stockId: "IMG-2021-000009",
    slug: "monastery-dawn",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Monastery at Dawn",
    subtitle: "Meteora, Greece · 2021",
    description: "Ancient monasteries perched impossibly atop towering sandstone pillars, emerging from morning mist as the first light strikes their stone facades.",
    imageContent: "Landscape photograph of Meteora monasteries at dawn, rock formations rising from a sea of clouds, warm light catching the Byzantine architecture.",
    displayPrice: "$449.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=90",
    width: 6000,
    height: 4000,
    resolution: "6000 × 4000",
    camera: "Nikon Z9",
    lens: "NIKKOR Z 24-70mm f/2.8 S",
    iso: "400",
    aperture: "f/5.6",
    focalLength: "35mm",
    shutterSpeed: "1/30s",
    country: "Greece",
    city: "Kalambaka",
    location: "Meteora",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "RIGHTS_MANAGED",
    views: 24100,
    likes: 2140,
    downloads: 389,
    favorites: 1120,
    popularity: 21000,
    shootDate: "2021-09-14",
    publishDate: "2021-09-20",
    createdAt: new Date("2021-09-20"),
    categoryName: "Travel",
    collectionName: "Sacred Light",
    tags: ["monastery", "greece", "landscape", "dawn", "ancient"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567010",
    publicId: "4710293856471",
    stockId: "IMG-2022-000010",
    slug: "market-spices-marrakech",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Spice Market Marrakech",
    subtitle: "Medina, Morocco · 2022",
    description: "The vibrant chaos of a traditional spice market in the medina of Marrakech. Mountains of powdered pigments create a visual feast of color and texture.",
    imageContent: "Top-down view of Moroccan spice market stalls, ceramic bowls filled with vibrant orange turmeric, red paprika, yellow saffron and green herbs in geometric arrangement.",
    displayPrice: "$219.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=1200&q=90",
    width: 5184,
    height: 3456,
    resolution: "5184 × 3456",
    camera: "Canon EOS R5",
    lens: "RF 35mm f/1.4L USM",
    iso: "200",
    aperture: "f/5.6",
    focalLength: "35mm",
    shutterSpeed: "1/200s",
    country: "Morocco",
    city: "Marrakech",
    location: "Djemaa el-Fna Medina",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "EDITORIAL",
    views: 11400,
    likes: 920,
    downloads: 178,
    favorites: 512,
    popularity: 9800,
    shootDate: "2022-03-18",
    publishDate: "2022-03-25",
    createdAt: new Date("2022-03-25"),
    categoryName: "Food & Culture",
    collectionName: "Craft & Tradition",
    tags: ["market", "morocco", "spices", "color", "documentary"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567011",
    publicId: "5934018274659",
    stockId: "IMG-2023-000011",
    slug: "fjord-reflection",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Fjord Reflection",
    subtitle: "Geiranger, Norway · 2023",
    description: "Mirror-still waters of the Geirangerfjord reflect an exact inverted world — mountain, sky, and village merged into one seamless composition.",
    imageContent: "Panoramic mirror reflection photograph of Norwegian fjord at sunrise, snow-capped mountains and small village reflected perfectly in glassy water.",
    displayPrice: "$379.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1529651737248-dad5e287768e?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1529651737248-dad5e287768e?w=1200&q=90",
    width: 7952,
    height: 4000,
    resolution: "7952 × 4000",
    camera: "Sony A7R V",
    lens: "FE 16-35mm f/2.8 GM II",
    iso: "100",
    aperture: "f/11",
    focalLength: "22mm",
    shutterSpeed: "1/15s",
    country: "Norway",
    city: "Geiranger",
    location: "Geirangerfjord",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "RIGHTS_MANAGED",
    views: 19800,
    likes: 1740,
    downloads: 321,
    favorites: 960,
    popularity: 17200,
    shootDate: "2023-06-05",
    publishDate: "2023-06-12",
    createdAt: new Date("2023-06-12"),
    categoryName: "Drone",
    collectionName: "Nordic Light",
    tags: ["fjord", "norway", "reflection", "landscape", "nordic"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567012",
    publicId: "8265194073821",
    stockId: "IMG-2023-000012",
    slug: "wildlife-elephant-savanna",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Elephant at Dusk",
    subtitle: "Amboseli, Kenya · 2023",
    description: "A lone elephant silhouetted against the burning amber sky at dusk, Mount Kilimanjaro rising in the haze behind — an image of ancient Africa.",
    imageContent: "Silhouette of African elephant walking across Amboseli savanna at dusk, Mount Kilimanjaro faintly visible through haze, dramatic orange and red sunset.",
    displayPrice: "$499.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1564760055775-d63b17a55c44?w=1200&q=90",
    width: 6000,
    height: 4000,
    resolution: "6000 × 4000",
    camera: "Canon EOS R3",
    lens: "RF 400mm f/2.8L IS USM",
    iso: "800",
    aperture: "f/4",
    focalLength: "400mm",
    shutterSpeed: "1/1000s",
    country: "Kenya",
    city: "Amboseli",
    location: "Amboseli National Park",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "RIGHTS_MANAGED",
    views: 27600,
    likes: 2420,
    downloads: 412,
    favorites: 1380,
    popularity: 24500,
    shootDate: "2023-08-22",
    publishDate: "2023-09-01",
    createdAt: new Date("2023-09-01"),
    categoryName: "Wildlife",
    collectionName: "Wild Africa",
    tags: ["wildlife", "elephant", "kenya", "africa", "safari"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567013",
    publicId: "1038274659102",
    stockId: "IMG-2024-000013",
    slug: "tokyo-neon-rain",
    type: "IMAGE",
    status: "PUBLISHED",
    title: "Neon Rain — Tokyo",
    subtitle: "Shinjuku, Japan · 2024",
    description: "A lone figure navigates the neon-soaked streets of Shinjuku under a transparent umbrella, the entire city reflected in the wet pavement below.",
    imageContent: "Street photograph at night in Shinjuku, person with umbrella walking past pink neon signage, their reflection perfectly mirrored in wet asphalt.",
    displayPrice: "$289.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=1200&q=90",
    width: 4000,
    height: 6000,
    resolution: "4000 × 6000",
    camera: "Leica M11",
    lens: "Summicron 35mm f/2",
    iso: "3200",
    aperture: "f/2.0",
    focalLength: "35mm",
    shutterSpeed: "1/30s",
    country: "Japan",
    city: "Tokyo",
    location: "Shinjuku",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "EDITORIAL",
    views: 16400,
    likes: 1380,
    downloads: 243,
    favorites: 720,
    popularity: 14000,
    shootDate: "2024-01-15",
    publishDate: "2024-01-22",
    createdAt: new Date("2024-01-22"),
    categoryName: "Street",
    collectionName: "Urban Stories",
    tags: ["street", "tokyo", "neon", "rain", "night"],
  },
  // VIDEO assets
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567014",
    publicId: "9182736405163",
    stockId: "VID-2022-000001",
    slug: "coastal-timelapse-portugal",
    type: "VIDEO",
    status: "PUBLISHED",
    title: "Atlantic Coast Timelapse",
    subtitle: "Alentejo Coast, Portugal · 2022",
    description: "A breathtaking 4K timelapse of the rugged Portuguese Atlantic coastline — waves crashing against ancient sea stacks over the course of a full day.",
    imageContent: "Timelapse footage of dramatic Atlantic waves crashing against tall sea stack formations, cloud movement creating dynamic sky, 16-hour capture compressed to 90 seconds.",
    displayPrice: "$599.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&q=90",
    width: 3840,
    height: 2160,
    resolution: "3840 × 2160",
    camera: "Sony FX6",
    lens: "FE 24mm f/1.4 GM",
    iso: "800",
    aperture: "f/8",
    country: "Portugal",
    city: "Comporta",
    location: "Alentejo Coast",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "RIGHTS_MANAGED",
    duration: 92,
    fps: "24fps",
    codec: "ProRes 4444",
    views: 14200,
    likes: 980,
    downloads: 87,
    favorites: 445,
    popularity: 11800,
    shootDate: "2022-10-08",
    publishDate: "2022-10-20",
    createdAt: new Date("2022-10-20"),
    categoryName: "Landscapes",
    collectionName: "Coastal Series",
    tags: ["timelapse", "ocean", "portugal", "4k", "atlantic"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567015",
    publicId: "6347291058274",
    stockId: "VID-2023-000002",
    slug: "urban-commute-tokyo",
    type: "VIDEO",
    status: "PUBLISHED",
    title: "Urban Commute — Tokyo",
    subtitle: "Shinjuku Station, Japan · 2023",
    description: "A cinematic short documentary capturing the extraordinary choreography of Tokyo's morning rush. 3.5 million people pass through Shinjuku Station daily.",
    displayPrice: "$449.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200&q=90",
    width: 3840,
    height: 2160,
    resolution: "3840 × 2160",
    camera: "Canon EOS C70",
    lens: "RF 28-70mm f/2L USM",
    iso: "1600",
    aperture: "f/2.8",
    country: "Japan",
    city: "Tokyo",
    location: "Shinjuku Station",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "EDITORIAL",
    duration: 187,
    fps: "30fps",
    codec: "H.265 (HEVC)",
    views: 9800,
    likes: 712,
    downloads: 56,
    favorites: 334,
    popularity: 8100,
    shootDate: "2023-03-10",
    publishDate: "2023-03-18",
    createdAt: new Date("2023-03-18"),
    categoryName: "Urban",
    collectionName: "Urban Stories",
    tags: ["documentary", "tokyo", "commute", "urban", "cinematic"],
  },
  {
    id: "a1b2c3d4-e5f6-7890-abcd-ef1234567016",
    publicId: "2847561930284",
    stockId: "VID-2024-000003",
    slug: "aurora-borealis-iceland",
    type: "VIDEO",
    status: "PUBLISHED",
    title: "Aurora Borealis — Iceland",
    subtitle: "Thingvellir, Iceland · 2024",
    description: "An otherworldly 4K cinematic sequence of the Northern Lights dancing over Iceland's volcanic landscape. Shot across three consecutive nights.",
    displayPrice: "$799.00",
    thumbnailUrl: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=600&q=80",
    previewUrl: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200&q=90",
    width: 3840,
    height: 2160,
    resolution: "3840 × 2160",
    camera: "Sony FX9",
    lens: "FE 14mm f/1.8 GM",
    iso: "6400",
    aperture: "f/1.8",
    country: "Iceland",
    city: "Thingvellir",
    location: "Þingvellir National Park",
    copyrightOwner: "ARCHI",
    copyrightYear: 2015,
    licenseType: "RIGHTS_MANAGED",
    duration: 214,
    fps: "24fps",
    codec: "ProRes RAW HQ",
    views: 31200,
    likes: 2890,
    downloads: 198,
    favorites: 1640,
    popularity: 28800,
    shootDate: "2024-02-14",
    publishDate: "2024-02-28",
    createdAt: new Date("2024-02-28"),
    categoryName: "Landscapes",
    collectionName: "Nordic Light",
    tags: ["aurora", "iceland", "northern lights", "4k", "cinematic"],
  },
];


const CATEGORY_DEFINITIONS = [
  { name: "Portraits", slug: "portraits", description: "Portraits shaped by character, place, and available light." },
  { name: "Architecture", slug: "architecture", description: "Built form, material, and proportion observed across cities." },
  { name: "Landscapes", slug: "landscapes", description: "Land, weather, and scale from coastlines to open desert." },
  { name: "Street", slug: "street", description: "Unscripted moments from public life." },
  { name: "Urban", slug: "urban", description: "Movement, infrastructure, and daily life in modern cities." },
  { name: "Documentary", slug: "documentary", description: "Visual records grounded in people, work, and place." },
  { name: "Fine Art", slug: "fine-art", description: "Form-led studies made for close and repeated viewing." },
  { name: "Travel", slug: "travel", description: "A considered record of destinations and local character." },
  { name: "Wildlife", slug: "wildlife", description: "Wild animals documented in their natural environments." },
  { name: "Macro", slug: "macro", description: "Small structures, textures, and natural details seen up close." },
  { name: "Food & Culture", slug: "food-culture", description: "Food traditions, markets, and the culture built around them." },
  { name: "Drone", slug: "drone", description: "Land and settlement photographed from above." },
] as const;

export const DEMO_CATEGORIES = CATEGORY_DEFINITIONS.map((category) => ({
  ...category,
  count: DEMO_IMAGES.filter((asset) => asset.categoryName === category.name).length,
}));

const COLLECTION_DEFINITIONS = [
  { id: "italian-light", name: "Italian Light", slug: "italian-light", count: 1, description: "A visual journey through the luminous quality of Italian light, from the golden coasts to Renaissance cities.", coverImage: null, sortOrder: 1 },
  { id: "modern-forms", name: "Modern Forms", slug: "modern-forms", count: 1, description: "Contemporary architecture and design that redefines urban landscapes.", coverImage: null, sortOrder: 2 },
  { id: "coastal-series", name: "Coastal Series", slug: "coastal-series", count: 3, description: "Where land meets sea — a meditation on coastal landscapes across continents.", coverImage: null, sortOrder: 3 },
  { id: "urban-stories", name: "Urban Stories", slug: "urban-stories", count: 3, description: "The human experience in the world's most dynamic urban environments.", coverImage: null, sortOrder: 4 },
  { id: "craft-tradition", name: "Craft & Tradition", slug: "craft-tradition", count: 2, description: "Preserving the legacy of traditional craftsmanship through visual storytelling.", coverImage: null, sortOrder: 5 },
  { id: "sacred-light", name: "Sacred Light", slug: "sacred-light", count: 1, description: "Ancient places of worship and pilgrimage, captured at the threshold of light and shadow.", coverImage: null, sortOrder: 6 },
  { id: "nordic-light", name: "Nordic Light", slug: "nordic-light", count: 2, description: "The extraordinary luminosity of Scandinavia — from the midnight sun to the aurora borealis.", coverImage: null, sortOrder: 7 },
  { id: "wild-africa", name: "Wild Africa", slug: "wild-africa", count: 1, description: "East Africa's iconic wildlife and landscapes across the great migration seasons.", coverImage: null, sortOrder: 8 },
];

export const DEMO_COLLECTIONS = COLLECTION_DEFINITIONS.map((collection) => ({
  ...collection,
  count: DEMO_IMAGES.filter((asset) => asset.collectionName === collection.name).length,
}));

export function getMockAssets(): MockAsset[] {
  return DEMO_IMAGES;
}

export function getMockAssetBySlug(slug: string): MockAsset | undefined {
  return DEMO_IMAGES.find(
    (a) => a.slug === slug || a.stockId === slug || a.id === slug
  );
}

export function getMockAssetsByType(type: "IMAGE" | "VIDEO"): MockAsset[] {
  return DEMO_IMAGES.filter((a) => a.type === type);
}

export function getMockAssetsByCategory(categorySlug: string): MockAsset[] {
  const cat = DEMO_CATEGORIES.find((c) => c.slug === categorySlug);
  if (!cat) return [];
  return DEMO_IMAGES.filter((a) => a.categoryName === cat.name);
}

export function getMockAssetsByCollection(collectionSlug: string): MockAsset[] {
  const col = DEMO_COLLECTIONS.find((c) => c.slug === collectionSlug);
  if (!col) return [];
  return DEMO_IMAGES.filter((a) => a.collectionName === col.name);
}

export function searchMockAssets(query: string): MockAsset[] {
  const q = query.toLowerCase();
  return DEMO_IMAGES.filter(
    (a) =>
      a.title.toLowerCase().includes(q) ||
      a.description.toLowerCase().includes(q) ||
      a.tags.some((t) => t.includes(q)) ||
      a.categoryName.toLowerCase().includes(q) ||
      a.country?.toLowerCase().includes(q) ||
      a.city?.toLowerCase().includes(q)
  );
}
