import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Bookmark, Calendar, ChevronRight, Download, Eye, Hash, Heart, MapPin, ShieldCheck } from "lucide-react";
import { getPublishedStory } from "@/lib/story-data";
import { LICENSE_TYPES } from "@/lib/constants";
import { formatNumber, formatUsd } from "@/lib/utils";
import { StorySlider } from "@/components/story-slider";

type Props = { params: Promise<{ slug: string; frame: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug, frame } = await params; const story = await getPublishedStory(slug); const index = Number(frame) - 1; if (!story || !story.images[index]) return { title: "Không tìm thấy" }; return { title: `${story.title} — ${frame}/${story.images.length}`, description: story.images[index].caption || story.excerpt, openGraph: { images: [story.images[index].url] } }; }

export default async function StoryFramePage({ params }: Props) {
  const { slug, frame } = await params; const story = await getPublishedStory(slug); const frameNumber = Number(frame);
  if (!story || !Number.isInteger(frameNumber) || frameNumber < 1 || frameNumber > story.images.length) notFound();
  const index = frameNumber - 1, image = story.images[index];
  const license = LICENSE_TYPES[story.licenseType as keyof typeof LICENSE_TYPES] || story.licenseType;
  const place = [story.location, story.city, story.country].filter(Boolean).join(", ");
  return <main className="museum-record"><nav className="container-wide border-b border-border pb-4 pt-6" aria-label="Breadcrumb"><ol className="flex items-center gap-1.5 text-xs text-muted"><li><Link href="/">Home</Link></li><li><ChevronRight size={12}/></li><li><Link href="/stories">Stories</Link></li><li><ChevronRight size={12}/></li><li className="truncate text-primary">{story.title}</li><li><ChevronRight size={12}/></li><li className="text-primary">Frame {frameNumber}</li></ol></nav>
    <div className="container-wide py-8 md:py-12"><div className="grid gap-10 lg:grid-cols-[minmax(0,1.7fr)_minmax(280px,.55fr)] lg:gap-16"><article><header className="mb-7 border-b border-border pb-6"><p className="text-caption mb-3">Visual story / Frame {String(frameNumber).padStart(2,"0")} of {story.images.length}</p><h1 className="font-editorial text-4xl font-normal leading-[.95] md:text-6xl">{story.title}</h1>{story.subtitle&&<p className="mt-3 text-sm text-muted">{story.subtitle}</p>}</header>
      <StorySlider slug={slug} title={story.title} slides={story.images} initialFrame={frameNumber}/>
      <div className="mt-4 flex flex-wrap items-center gap-6 border-y border-border py-3 text-sm text-secondary"><span className="flex gap-1.5"><Eye size={15}/>{formatNumber(story.views)} views</span><span className="flex gap-1.5"><Heart size={15}/>{formatNumber(story.likes)} likes</span><span className="flex gap-1.5"><Download size={15}/>{formatNumber(story.downloads)} downloads</span><span className="flex gap-1.5"><Bookmark size={15}/>{formatNumber(story.favorites)} favorites</span></div>
      {story.excerpt&&<p className="mt-8 max-w-3xl leading-7 text-secondary">{story.excerpt}</p>}{story.content&&<section className="mt-8 border-t border-border pt-7"><p className="text-caption">Archive note</p><p className="mt-3 max-w-3xl whitespace-pre-line leading-7 text-secondary">{story.content}</p></section>}</article>
      <aside className="space-y-6"><div className="border border-border bg-surface p-6"><p className="text-caption">Story record</p><p className="mt-1 text-2xl font-bold">{frameNumber} / {story.images.length}</p>{story.displayPrice&&<p className="mt-3 text-lg font-semibold">{formatUsd(story.displayPrice)}</p>}</div><div className="border border-burnt-orange/20 bg-burnt-orange/5 p-6"><div className="mb-4 flex items-center gap-2"><ShieldCheck size={18} className="text-burnt-orange"/><h2 className="text-sm font-semibold">Copyright & License</h2></div><dl className="space-y-3 text-sm"><Row label="Copyright owner" value={story.copyrightOwner||"Not specified"}/><Row label="License" value={license||"Not specified"}/><Row label="Archive" value="Official Digital Archive"/>{story.contactEmail&&<Row label="Contact" value={story.contactEmail}/>}</dl></div><div className="border border-border bg-surface p-6"><h2 className="mb-4 text-sm font-semibold">Frame Information</h2><dl className="space-y-3 text-sm"><Row icon={<Hash size={13}/>} label="Frame ID" value={image.id.slice(0,8).toUpperCase()}/><Row label="Resolution" value={`${image.width} × ${image.height}`}/><Row label="File size" value={image.fileSize?`${(image.fileSize/1024/1024).toFixed(2)} MB`:"Remote"}/><Row icon={<Calendar size={13}/>} label="Published" value={story.publishedAt?.toLocaleDateString("vi-VN")||"Not set"}/><Row icon={<Calendar size={13}/>} label="Archived" value={story.archiveDate?.toLocaleDateString("vi-VN")||"Not set"}/>{place&&<Row icon={<MapPin size={13}/>} label="Location" value={place}/>}<Row label="Category" value={story.category||"Uncategorized"}/></dl></div></aside></div></div></main>;
}
function Row({label,value,icon}:{label:string;value:string;icon?:React.ReactNode}){return <div className="flex justify-between gap-4"><dt className="flex items-center gap-1.5 text-muted">{icon}{label}</dt><dd className="max-w-[60%] text-right font-medium">{value}</dd></div>}
