"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { AlertCircle, ArrowDown, ArrowUp, ImagePlus, LoaderCircle, Trash2 } from "lucide-react";
import { uploadManyToCloudinary } from "@/lib/cloudinary-client";
import { DEMO_CATEGORIES } from "@/lib/mock-data";

type ExistingImage = { id: string; url: string; alt: string | null; caption: string | null; width: number; height: number };
type StoryInitial = { id: string; title: string; subtitle: string | null; slug: string; excerpt: string | null; content: string | null; category: string | null; tags: string | null; country: string | null; city: string | null; location: string | null; status: "DRAFT" | "PUBLISHED" | "ARCHIVED"; publishedAt: string | null; archiveDate: string | null; licenseType: "RIGHTS_MANAGED" | "ROYALTY_FREE" | "EDITORIAL" | "PERSONAL" | "COMMERCIAL"; copyrightOwner: string | null; contactEmail: string | null; contactWebsite: string | null; displayPrice: string | null; views: number; likes: number; downloads: number; favorites: number; seoTitle: string | null; seoDescription: string | null; images: ExistingImage[] };
type ImageItem = { key: string; id?: string; file?: File; url: string; alt: string; caption: string; width: number; height: number };

function readDimensions(file: File) {
  return new Promise<{ width: number; height: number; url: string }>((resolve, reject) => {
    const url = URL.createObjectURL(file); const image = new window.Image();
    image.onload = () => resolve({ width: image.naturalWidth, height: image.naturalHeight, url });
    image.onerror = () => { URL.revokeObjectURL(url); reject(new Error(`Không thể đọc ảnh ${file.name}`)); }; image.src = url;
  });
}

export function StoryForm({ initial }: { initial?: StoryInitial }) {
  const router = useRouter();
  const [fields, setFields] = useState({ title: initial?.title || "", subtitle: initial?.subtitle || "", slug: initial?.slug || "", excerpt: initial?.excerpt || "", content: initial?.content || "", category: initial?.category || "", tags: initial?.tags || "", country: initial?.country || "", city: initial?.city || "", location: initial?.location || "", status: initial?.status || "DRAFT", publishedAt: initial?.publishedAt?.slice(0,10) || new Date().toISOString().slice(0,10), archiveDate: initial?.archiveDate?.slice(0,10) || new Date().toISOString().slice(0,10), licenseType: initial?.licenseType || "RIGHTS_MANAGED", copyrightOwner: initial?.copyrightOwner || "", contactEmail: initial?.contactEmail || "", contactWebsite: initial?.contactWebsite || "", displayPrice: initial?.displayPrice || "", views: String(initial?.views || 0), likes: String(initial?.likes || 0), downloads: String(initial?.downloads || 0), favorites: String(initial?.favorites || 0), seoTitle: initial?.seoTitle || "", seoDescription: initial?.seoDescription || "" });
  const [images, setImages] = useState<ImageItem[]>(() => initial?.images.map((image) => ({ key: image.id, id: image.id, url: image.url, alt: image.alt || "", caption: image.caption || "", width: image.width, height: image.height })) || []);
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const addFiles = async (files: FileList | null) => {
    if (!files) return; setError("");
    const selected = [...files]; if (images.length + selected.length > 25) return setError("Mỗi bài viết chỉ được tối đa 25 ảnh.");
    try { const loaded = await Promise.all(selected.map(async (file) => ({ key: crypto.randomUUID(), file, alt: "", caption: "", ...(await readDimensions(file)) }))); setImages((current) => [...current, ...loaded]); }
    catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Không thể đọc ảnh"); }
  };
  const move = (index: number, delta: number) => setImages((current) => { const next = [...current]; const target = index + delta; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const updateImage = (key: string, name: "alt" | "caption", value: string) => setImages((current) => current.map((image) => image.key === key ? { ...image, [name]: value } : image));

  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setError(""); if (!images.length) return setError("Hãy thêm ít nhất 1 ảnh."); setSaving(true);
    const body = new FormData(); Object.entries(fields).forEach(([key, value]) => body.set(key, value));
    const newImages = images.filter((image) => image.file); newImages.forEach((image) => body.append("images", image.file!));
    body.set("imageMeta", JSON.stringify(newImages.map(({ alt, caption, width, height }) => ({ alt, caption, width, height }))));
    body.set("keepImageIds", JSON.stringify(images.flatMap((image) => image.id ? [image.id] : [])));
    body.set("existingMeta", JSON.stringify(Object.fromEntries(images.filter((image) => image.id).map((image) => [image.id!, { alt: image.alt, caption: image.caption }]))));
    try { const uploaded = await uploadManyToCloudinary(newImages.map((image) => image.file!), "archi/stories"); body.delete("images"); body.set("remoteImages", JSON.stringify(uploaded.map((item,index)=>({ url:item.url, path:`cloudinary:${item.resourceType}:${item.publicId}`, width:item.width, height:item.height, fileSize:item.bytes, alt:newImages[index].alt, caption:newImages[index].caption })))); const response = await fetch(initial ? `/api/admin/stories/${initial.id}` : "/api/admin/stories", { method: initial ? "PUT" : "POST", body }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Không thể lưu bài viết"); router.push("/admin/stories"); router.refresh(); }
    catch (submitError) { setError(submitError instanceof Error ? submitError.message : "Không thể lưu bài viết"); } finally { setSaving(false); }
  };

  return <form onSubmit={submit} className="space-y-8">
    <section className="grid gap-5 rounded-lg border border-border bg-surface p-5 md:grid-cols-2">
      <label className="text-sm font-semibold text-primary md:col-span-2">Tiêu đề<input required maxLength={160} value={fields.title} onChange={(e)=>setFields({...fields,title:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label>
      <label className="text-sm font-semibold text-primary md:col-span-2">Phụ đề<input maxLength={240} value={fields.subtitle} onChange={(e)=>setFields({...fields,subtitle:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label>
      <label className="text-sm font-semibold text-primary">Slug<input value={fields.slug} onChange={(e)=>setFields({...fields,slug:e.target.value})} placeholder="tự tạo từ tiêu đề" className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label>
      <label className="text-sm font-semibold text-primary">Trạng thái<select value={fields.status} onChange={(e)=>setFields({...fields,status:e.target.value as typeof fields.status})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"><option value="DRAFT">Bản nháp</option><option value="PUBLISHED">Xuất bản</option><option value="ARCHIVED">Lưu trữ</option></select></label>
      <label className="text-sm font-semibold">Ngày xuất bản<input type="date" value={fields.publishedAt} onChange={(e)=>setFields({...fields,publishedAt:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label>
      <label className="text-sm font-semibold">Ngày lưu trữ<input type="date" value={fields.archiveDate} onChange={(e)=>setFields({...fields,archiveDate:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label>
      <label className="text-sm font-semibold text-primary md:col-span-2">Mô tả ngắn<textarea maxLength={500} rows={3} value={fields.excerpt} onChange={(e)=>setFields({...fields,excerpt:e.target.value})} className="mt-2 w-full resize-y rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label>
      <label className="text-sm font-semibold text-primary md:col-span-2">Nội dung<textarea maxLength={10000} rows={7} value={fields.content} onChange={(e)=>setFields({...fields,content:e.target.value})} className="mt-2 w-full resize-y rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label>
    </section>
    <section className="grid gap-5 rounded-lg border border-border bg-surface p-5 md:grid-cols-2"><h2 className="text-lg font-bold md:col-span-2">Phân loại và địa điểm</h2><label className="text-sm font-semibold">Danh mục<select value={fields.category} onChange={(e)=>setFields({...fields,category:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"><option value="">Chọn danh mục</option>{DEMO_CATEGORIES.map((item)=><option key={item.slug} value={item.name}>{item.name}</option>)}</select></label><label className="text-sm font-semibold">Thẻ<input value={fields.tags} onChange={(e)=>setFields({...fields,tags:e.target.value})} placeholder="phân cách bằng dấu phẩy" className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Quốc gia<input value={fields.country} onChange={(e)=>setFields({...fields,country:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Thành phố<input value={fields.city} onChange={(e)=>setFields({...fields,city:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold md:col-span-2">Địa điểm cụ thể<input value={fields.location} onChange={(e)=>setFields({...fields,location:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label></section>
    <section className="grid gap-5 rounded-lg border border-border bg-surface p-5 md:grid-cols-2"><h2 className="text-lg font-bold md:col-span-2">Bản quyền và thống kê</h2><label className="text-sm font-semibold">Giấy phép<select value={fields.licenseType} onChange={(e)=>setFields({...fields,licenseType:e.target.value as typeof fields.licenseType})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"><option value="RIGHTS_MANAGED">Quản lý quyền</option><option value="ROYALTY_FREE">Miễn phí bản quyền</option><option value="EDITORIAL">Biên tập</option><option value="PERSONAL">Cá nhân</option><option value="COMMERCIAL">Thương mại</option></select></label><label className="text-sm font-semibold">Giá hiển thị (USD)<input type="number" min="0" step="0.01" value={fields.displayPrice} onChange={(e)=>setFields({...fields,displayPrice:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Chủ sở hữu<input value={fields.copyrightOwner} onChange={(e)=>setFields({...fields,copyrightOwner:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Email liên hệ<input type="email" value={fields.contactEmail} onChange={(e)=>setFields({...fields,contactEmail:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Website liên hệ<input type="url" value={fields.contactWebsite} onChange={(e)=>setFields({...fields,contactWebsite:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Lượt xem<input type="number" min="0" value={fields.views} onChange={(e)=>setFields({...fields,views:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Lượt thích<input type="number" min="0" value={fields.likes} onChange={(e)=>setFields({...fields,likes:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Lượt tải<input type="number" min="0" value={fields.downloads} onChange={(e)=>setFields({...fields,downloads:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label><label className="text-sm font-semibold">Lượt lưu<input type="number" min="0" value={fields.favorites} onChange={(e)=>setFields({...fields,favorites:e.target.value})} className="mt-2 w-full rounded-md border border-border bg-bg px-3 py-2.5 font-normal"/></label></section>
    <section><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Ảnh trong bài</h2><p className="text-sm text-secondary">{images.length}/25 ảnh · tải trực tiếp lên Cloudinary · tối đa 10 MB/ảnh</p></div><label className="inline-flex cursor-pointer items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-surface"><ImagePlus size={17}/>Thêm ảnh<input type="file" multiple accept="image/jpeg,image/png,image/webp,image/avif" className="sr-only" onChange={(e)=>{void addFiles(e.target.files); e.target.value="";}}/></label></div>
      <div className="space-y-3">{images.map((image,index)=><article key={image.key} className="grid gap-4 rounded-lg border border-border bg-surface p-3 sm:grid-cols-[120px_1fr_auto]"><div className="relative aspect-square overflow-hidden rounded-md bg-border-light"><Image src={image.url} alt="" fill sizes="120px" unoptimized={image.url.startsWith("blob:")} className="object-cover"/></div><div className="grid content-center gap-3"><input value={image.alt} maxLength={240} onChange={(e)=>updateImage(image.key,"alt",e.target.value)} placeholder="Alt text mô tả ảnh" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><input value={image.caption} maxLength={1000} onChange={(e)=>updateImage(image.key,"caption",e.target.value)} placeholder="Chú thích (không bắt buộc)" className="rounded-md border border-border bg-bg px-3 py-2 text-sm"/><span className="text-xs text-muted">{image.width} × {image.height}{image.file ? ` · ${(image.file.size/1024/1024).toFixed(1)} MB` : ""}</span></div><div className="flex gap-1 sm:flex-col"><button type="button" title="Đưa lên" disabled={index===0} onClick={()=>move(index,-1)} className="rounded-md p-2 hover:bg-border-light disabled:opacity-25"><ArrowUp size={17}/></button><button type="button" title="Đưa xuống" disabled={index===images.length-1} onClick={()=>move(index,1)} className="rounded-md p-2 hover:bg-border-light disabled:opacity-25"><ArrowDown size={17}/></button><button type="button" title="Xóa ảnh" onClick={()=>setImages(images.filter((item)=>item.key!==image.key))} className="rounded-md p-2 text-red-600 hover:bg-red-500/10"><Trash2 size={17}/></button></div></article>)}</div>
    </section>
    <details className="rounded-lg border border-border bg-surface p-5"><summary className="cursor-pointer font-semibold">SEO</summary><div className="mt-4 grid gap-4"><input maxLength={160} value={fields.seoTitle} onChange={(e)=>setFields({...fields,seoTitle:e.target.value})} placeholder="SEO title" className="rounded-md border border-border bg-bg px-3 py-2.5"/><textarea maxLength={320} value={fields.seoDescription} onChange={(e)=>setFields({...fields,seoDescription:e.target.value})} placeholder="SEO description" rows={3} className="rounded-md border border-border bg-bg px-3 py-2.5"/></div></details>
    {error&&<p role="alert" className="flex gap-2 rounded-md border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-600"><AlertCircle size={17}/>{error}</p>}
    <div className="flex justify-end gap-3 border-t border-border pt-5"><button type="button" onClick={()=>router.back()} className="rounded-md border border-border px-5 py-2.5 text-sm font-semibold">Hủy</button><button disabled={saving} className="inline-flex items-center gap-2 rounded-md bg-burnt-orange px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving&&<LoaderCircle size={17} className="animate-spin"/>}{saving?"Đang lưu...":"Lưu bài viết"}</button></div>
  </form>;
}
